services:
  # traefik:
  #   image: traefik:v2.9
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   networks:
  #     - project_network

  # webapp:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: webapp
  #   ports:
  #     - "0.0.0.0:8000:8000" # Bind to all interfaces
  #   networks:
  #     - project_network
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.webapp.rule=Host(`kanapi.local`)"
  #     - "traefik.http.routers.webapp.entrypoints=web"
  #     - "traefik.http.services.webapp.loadbalancer.server.port=8000"
  # redis:
  #   image: redis:8.2-m01-alpine3.22
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - project_networ

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - project_network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - project_network

  openfga-db:
    image: postgres:17
    container_name: openfga-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openfga
    ports:
      - "5433:5432"
    networks:
      - project_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga-migrate:
    image: openfga/openfga:latest
    container_name: openfga-migrate
    depends_on:
      openfga-db:
        condition: service_healthy
    command: migrate
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: "postgres://postgres:password@openfga-db:5432/openfga?sslmode=disable"
    networks:
      - project_network

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: "postgres://postgres:password@openfga-db:5432/openfga?sslmode=disable"
    command: run
    networks:
      - project_network

volumes:
  # redis-data:
  #   driver: local
  data:
    driver: local
  minio-data:
    driver: local
networks:
  project_network:
    driver: bridge
